create table ALL_Documento (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, fechaVencimiento timestamp, fileLength int4 not null, fileName varchar(255) not null, observacion varchar(255), optLock int4, tipoDocumento_id int8 not null, primary key (id));
create table ALL_NotaTecnica (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, observacion varchar(1024), optLock int4, primary key (id));
create table ALL_Observacion (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, observacion varchar(1024), optLock int4, primary key (id));
create table ALL_TipoDocumento (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, modulo varchar(255), nombre varchar(120), OPTLOCK int4, primary key (id));
create table ALL_ValoresEstandares (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, iva float8, optLock int4, secPoliza int8, secRecibo int8, ut float8, primary key (id));
create table ASEG_Asegurado (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, fechaEgresoFondo date, fechaIngresoFondo date, optLock int4, primaAporte float8, primaAsegurado float8, primaTotal float8, certificado_id int8, parentesco_id int8, persona_id int8, plan_id int8, plazoEspera_id int8, primary key (id));
create table ASEG_Asegurado_ALL_Documento (ASEG_Asegurado_id int8 not null, documentos_id int8 not null, primary key (ASEG_Asegurado_id, documentos_id), unique (documentos_id));
create table ASEG_Asegurado_ALL_NotaTecnica (ASEG_Asegurado_id int8 not null, notasTecnicas_id int8 not null, unique (notasTecnicas_id));
create table ASEG_Asegurado_ALL_Observacion (ASEG_Asegurado_id int8 not null, observaciones_id int8 not null, unique (observaciones_id));
create table ASEG_Beneficiario (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, indemnizacion float8, optLock int4, certificado_id int8, persona_id int8, primary key (id));
create table ASEG_Beneficiario_ALL_Documento (ASEG_Beneficiario_id int8 not null, documentos_id int8 not null, primary key (ASEG_Beneficiario_id, documentos_id), unique (documentos_id));
create table ASEG_Beneficiario_ALL_NotaTecnica (ASEG_Beneficiario_id int8 not null, notasTecnicas_id int8 not null, unique (notasTecnicas_id));
create table ASEG_Beneficiario_ALL_Observacion (ASEG_Beneficiario_id int8 not null, observaciones_id int8 not null, unique (observaciones_id));
create table ASEG_Certificado (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, fechaPrimaHCM time, fechaPrimaVida time, optLock int4, titular_id int8, primary key (id));
create table ASEG_Certificado_ALL_Documento (ASEG_Certificado_id int8 not null, documentos_id int8 not null, primary key (ASEG_Certificado_id, documentos_id), unique (documentos_id));
create table ASEG_Certificado_ALL_NotaTecnica (ASEG_Certificado_id int8 not null, notasTecnicas_id int8 not null, unique (notasTecnicas_id));
create table ASEG_Certificado_ALL_Observacion (ASEG_Certificado_id int8 not null, observaciones_id int8 not null, unique (observaciones_id));
create table ASEG_Departamento (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, nombre varchar(255), optLock int4, primary key (id));
create table ASEG_Parentesco (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, hcm bool, nombre varchar(255), optLock int4, vida bool, primary key (id));
create table ASEG_Plan (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, nombre varchar(255), optLock int4, primary key (id));
create table ASEG_PlazoEspera (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, nombre varchar(255), optLock int4, primary key (id));
create table ASEG_Poliza (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, ayudaSocial bool, fechaComienzo timestamp, nombre varchar(255), numero varchar(255), optLock int4, vigenciaDesde timestamp, vigenciaHasta timestamp, primary key (id));
create table ASEG_Poliza_ALL_Documento (ASEG_Poliza_id int8 not null, documentos_id int8 not null, primary key (ASEG_Poliza_id, documentos_id), unique (documentos_id));
create table ASEG_Poliza_ALL_NotaTecnica (ASEG_Poliza_id int8 not null, notasTecnicas_id int8 not null, unique (notasTecnicas_id));
create table ASEG_Poliza_ALL_Observacion (ASEG_Poliza_id int8 not null, observaciones_id int8 not null, unique (observaciones_id));
create table ASEG_Poliza_ASEG_Certificado (ASEG_Poliza_id int8 not null, certificados_id int8 not null, primary key (ASEG_Poliza_id, certificados_id));
create table ASEG_TipoContrato (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, nombre varchar(255), optLock int4, primary key (id));
create table ASEG_Titular (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, codigoEmpleado varchar(255), fechaInduccion date, fechaIngresoEmpresa date, optLock int4, departamento_id int8, persona_id int8, tipoContrato_id int8, primary key (id));
create table ASEG_Titular_ALL_Documento (ASEG_Titular_id int8 not null, documentos_id int8 not null, primary key (ASEG_Titular_id, documentos_id), unique (documentos_id));
create table ASEG_Titular_ALL_NotaTecnica (ASEG_Titular_id int8 not null, notasTecnicas_id int8 not null, unique (notasTecnicas_id));
create table ASEG_Titular_ALL_Observacion (ASEG_Titular_id int8 not null, observaciones_id int8 not null, unique (observaciones_id));
create table CONF_ConceptoSENIAT (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, codigo varchar(255), nombre varchar(255), optLock int4, porcentajeRetencionIslr float8, primary key (id));
create table CONF_ConfiguracionPrima (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, baseInponible bool, islr bool, iva bool, optLock int4, edadDesde int4, edadHasta int4, maternidad bool, primaAporte float8, primaAsegurado float8, primaTotal float8, sexo varchar(255), cobertura_id int8, parentesco_id int8, primary key (id));
create table CONF_Ramo (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, idPropio varchar(120) unique, nombre varchar(120) unique, optLock int4, primary key (id));
create table CONF_SumaAmparada (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, monto float8, nombre varchar(255), optLock int4, plan_id int8 not null, primary key (id));
create table CONF_SumaAsegurada (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, optLock int4, diagnostico_id int8, plan_id int8 not null, sumaAmparada_id int8, primary key (id));
create table PAGO_OrdenDePago (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, autoSearch bool, codigoSIGECOF varchar(255), estatusPago varchar(255), fechaPago date, numeroOrden varchar(255), optLock int4, referencia varchar(255), personaPago_id int8, primary key (id));
create table PAGO_OrdenDePago_ALL_Documento (PAGO_OrdenDePago_id int8 not null, documentos_id int8 not null, primary key (PAGO_OrdenDePago_id, documentos_id), unique (documentos_id));
create table PAGO_OrdenDePago_ALL_NotaTecnica (PAGO_OrdenDePago_id int8 not null, notasTecnicas_id int8 not null, unique (notasTecnicas_id));
create table PAGO_OrdenDePago_ALL_Observacion (PAGO_OrdenDePago_id int8 not null, observaciones_id int8 not null, unique (observaciones_id));
create table PAGO_OrdenDePago_SINI_DetalleSiniestro (PAGO_OrdenDePago_id int8 not null, detalleSiniestros_id int8 not null, primary key (PAGO_OrdenDePago_id, detalleSiniestros_id), unique (detalleSiniestros_id));
create table PAGO_Remesa (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, estatusPago varchar(255), fechaPagoRemesa date, numeroRemesa varchar(255), optLock int4, primary key (id));
create table PAGO_Remesa_PAGO_OrdenDePago (PAGO_Remesa_id int8 not null, ordenDePagos_id int8 not null, primary key (PAGO_Remesa_id, ordenDePagos_id), unique (ordenDePagos_id));
create table PERS_CuentaBancariaPersona (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, numero varchar(50), observacion varchar(255), optLock int4, banco_id int8 not null, tipoCuenta_id int8 not null, primary key (id), unique (numero, banco_id, tipoCuenta_id));
create table PERS_DIR_Estado (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, nombre varchar(120), optLock int4, primary key (id));
create table PERS_DefaultPersona (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, optLock int4, actividadEconomica_id int8, capacidadEconomica_id int8, direccion_id int8, telefono_id int8, primary key (id));
create table PERS_DireccionPersona (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, direccion varchar(255), latitud float4, longitud float4, observacion varchar(255), OPTLOCK int4, zonaPostal varchar(255), tipoDireccion_id int8 not null, primary key (id));
create table PERS_Persona (id int8 not null, alias2 varchar(255), activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, codigoArchivo varchar(255), codigoX varchar(255), email varchar(255), fechaUltimoBalance date, gobierno bool, nombreCorto varchar(255), nombreLargo varchar(240), optLock int4, ranking varchar(255), cedulaCompleta varchar(255), finRif int4, numeroCedula int4, rif varchar(255), secuencia int4, tipoCedula varchar(255), tipoContribuyente varchar(255), web varchar(255), actividadEconomica_id int8, capacidadEconomica_id int8, primary key (id));
create table PERS_PersonaJuridica (fechaRegistro date, montoCapitalPagado float8, montoCapitalSuscrito float8, montoPatrimonioNeto float8, numeroGaceta varchar(255), numeroRegistro varchar(255), numeroTomo varchar(255), id int8 not null, primary key (id));
create table PERS_PersonaNatural (ciudadNacimiento varchar(255), estadoCivil varchar(255), estadoNacimiento varchar(255), estatura float4, fechaNacimiento date, nombreCasada varchar(255), ocupacion varchar(255), peso float4, primerApellido varchar(40), primerNombre varchar(40), profecion varchar(255), segundoApellido varchar(40), segundoNombre varchar(40), sexo varchar(255) not null, tipoNombre varchar(255), id int8 not null, primary key (id));
create table PERS_Persona_ALL_Documento (PERS_Persona_id int8 not null, documentos_id int8 not null, primary key (PERS_Persona_id, documentos_id), unique (documentos_id));
create table PERS_Persona_ALL_Observacion (PERS_Persona_id int8 not null, observaciones_id int8 not null, primary key (PERS_Persona_id, observaciones_id), unique (observaciones_id));
create table PERS_Persona_PERS_CuentaBancariaPersona (PERS_Persona_id int8 not null, cuentasBancarias_id int8 not null, primary key (PERS_Persona_id, cuentasBancarias_id), unique (cuentasBancarias_id));
create table PERS_Persona_PERS_DireccionPersona (PERS_Persona_id int8 not null, direcciones_id int8 not null, primary key (PERS_Persona_id, direcciones_id), unique (direcciones_id));
create table PERS_Persona_PERS_Sucursal (PERS_Persona_id int8 not null, sucursales_id int8 not null, primary key (PERS_Persona_id, sucursales_id), unique (sucursales_id));
create table PERS_Persona_PERS_TelefonoPersona (PERS_Persona_id int8 not null, telefonos_id int8 not null, primary key (PERS_Persona_id, telefonos_id), unique (telefonos_id));
create table PERS_Persona_PERS_TipoPersona (PERS_Persona_id int8 not null, tiposPersona_id int8 not null, primary key (PERS_Persona_id, tiposPersona_id));
create table PERS_Sucursal (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, nombre varchar(120), observacion varchar(255), optLock int4, primary key (id));
create table PERS_Sucursal_PERS_DireccionPersona (PERS_Sucursal_id int8 not null, direcciones_id int8 not null, primary key (PERS_Sucursal_id, direcciones_id), unique (direcciones_id));
create table PERS_Sucursal_PERS_TelefonoPersona (PERS_Sucursal_id int8 not null, telefonos_id int8 not null, primary key (PERS_Sucursal_id, telefonos_id), unique (telefonos_id));
create table PERS_TELF_TipoCodigoArea (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, nombre varchar(120), numero int4 check (numero<=999), optLock int4, primary key (id));
create table PERS_TelefonoPersona (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, notificar bool, numeroCompleto varchar(255) not null, numeroS varchar(255), observacion varchar(255), optLock int4, codigoArea_id int8 not null, tipoTelefono_id int8 not null, primary key (id));
create table PERS_TipoActividadEconomica (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, nombre varchar(120), optLock int4, primary key (id));
create table PERS_TipoCapacidadEconomica (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, nombre varchar(120), optLock int4, primary key (id));
create table PERS_TipoCuentaBancaria (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, nombre varchar(120), optLock int4, primary key (id));
create table PERS_TipoDireccion (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, nombre varchar(120), optLock int4, primary key (id));
create table PERS_TipoPersona (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, bloqueado bool, idPropio varchar(10) unique, nombre varchar(120), optLock int4, primary key (id));
create table PERS_TipoTelefono (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, nombre varchar(120), optLock int4, primary key (id));
create table SINI_Cobertura (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, nombre varchar(120), optLock int4, ramo_id int8 not null, primary key (id));
create table SINI_DesgloseCobertura (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, detalle varchar(255), montoAmparado float8, montoFacturado float8, montoNoAmparado float8, optLock int4, cobertura_id int8, primary key (id));
create table SINI_DesgloseSumaAsegurada (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, detalle varchar(255), monto float8, optLock int4, diagnosticoSiniestro_id int8, factura_id int8, primary key (id));
create table SINI_DetalleSiniestro (DTYPE varchar(31) not null, id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, fechaLiquidado timestamp, montoFacturado float8, montoLiquidado float8, numero int4, optLock int4, presupuestadoAjustado float8, presupuestadoInicial float8, tipoEnfermedad varchar(255), tratamientoEfectuado varchar(255), fechaEmision date, fechaVencimiento date, clave varchar(255), fechaEntrada date, fechaSalida date, nombreContacto varchar(255), telefonoContacto varchar(255), fechaDefuncion date, fechaConstitucion date, fechaNotificacion date, fechaOcurrencia date, analistaNegociador_id int8, etapaSiniestro_id int8, personaPago_id int8, ramo_id int8, siniestro_id int8, tipoPersona_id int8, tipoSiniestro_id int8, primary key (id));
create table SINI_DetalleSiniestro_ALL_Documento (SINI_DetalleSiniestro_id int8 not null, documentos_id int8 not null, primary key (SINI_DetalleSiniestro_id, documentos_id), unique (documentos_id));
create table SINI_DetalleSiniestro_ALL_NotaTecnica (SINI_DetalleSiniestro_id int8 not null, notasTecnicas_id int8 not null, unique (notasTecnicas_id));
create table SINI_DetalleSiniestro_ALL_Observacion (SINI_DetalleSiniestro_id int8 not null, observaciones_id int8 not null, unique (observaciones_id));
create table SINI_Diagnostico (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, nombre varchar(255), optLock int4, especialidad_id int8 not null, primary key (id));
create table SINI_DiagnosticoSiniestro (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, montoPagado float8, montoPendiente float8, optLock int4, tratamientoEscrito varchar(255), detalleSiniestro_id int8, diagnostico_id int8, primary key (id));
create table SINI_DiagnosticoSiniestro_SINI_Tratamiento (SINI_DiagnosticoSiniestro_id int8 not null, tratamientos_id int8 not null, primary key (SINI_DiagnosticoSiniestro_id, tratamientos_id));
create table SINI_Especialidad (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, nombre varchar(255), optLock int4, ramo_id int8, primary key (id));
create table SINI_EstatusSiniestro (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, nombre varchar(255), optLock int4, primary key (id));
create table SINI_EtapaSiniestro (id int8 not null, aps bool, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, ayudaSocial bool, cartaAval bool, emergencia bool, funerario bool, idPropio varchar(255), nombre varchar(255), optLock int4, reembolso bool, vida bool, estatusSiniestro_id int8, primary key (id));
create table SINI_Factura (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, estatusPago varchar(255) not null, fechaFactura date, fechaPagado date, fechaRecepcion date, fechaSeleccionado date, gastosClinicos float8, honorariosMedicos float8, montoDescuentoDesducible float8, montoDescuentoProntoPago float8, montoIva float8, montoNoAmparado float8, montoRetencionIva float8, montoReteniconIsrl float8, montoSujetoRetencion float8, montoTM float8, numeroControl varchar(255), numeroFactura varchar(255), optLock int4, porcenajeRetencionIva float8, porcentajeTM float8, posentajeReteniconIsrl float8, procentajeIva float8, sustraendo float8, totalACancelar float8, totalFacturado float8, totalLiquidado float8, totalRetenido float8, valorUT float8, detalleSiniestro_id int8, tipoConceptoSeniat_id int8, primary key (id));
create table SINI_Factura_SINI_DesgloseCobertura (SINI_Factura_id int8 not null, desgloseCobertura_id int8 not null, primary key (SINI_Factura_id, desgloseCobertura_id), unique (desgloseCobertura_id));
create table SINI_MantenimientoDiagnostico (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, justificacion varchar(255), montoActual float8, montoAnterior float8, optLock int4, diagnosticoSiniestro_id int8, primary key (id));
create table SINI_Presupuesto (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, fecha date, optLock int4, presupuestadoAjustado float8, presupuestadoInicial float8, analistaNegociador_id int8, primary key (id));
create table SINI_Siniestro (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, ayo int4, mes int4, montoTotal float8, numero varchar(255), optLock int4, seq int8, asegurado_id int8, certificado_id int8, primary key (id));
create table SINI_TipoSiniestro (id int8 not null, aps bool, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, ayudaSocial bool, cartaAval bool, emergencia bool, funerario bool, nombre varchar(255), optLock int4, reembolso bool, vida bool, primary key (id));
create table SINI_Tratamiento (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, nombre varchar(255), optLock int4, diagnostico_id int8, primary key (id));
create table SYST_AudiLogRecord (id int8 not null, created timestamp, entityClass varchar(255), entityId int8, ips varchar(255), message varchar(255), nombres bytea, user2 varchar(255), userOS varchar(255), valores bytea, primary key (id));
create table SYST_CalendarioBancario (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, bancario bool, fecha timestamp, nacional bool, nombre varchar(120), observacion varchar(255), optLock int4, regional bool, primary key (id));
create table SYST_Empresa (id int8 not null, direccion varchar(255), email varchar(255), emailEmpresaSoporte varchar(255) not null, emailSistemaSoporte varchar(255) not null, fileGridProfileManager bool, nombre varchar(240), optLock int4, rif2 varchar(255), rutaDocDigitales varchar(255), rutaReportes varchar(255), telefonos varchar(255), textoMayuscula bool, usosDisponibles int4, web varchar(255), primary key (id));
create table SYST_Encabezado (id int8 not null, imagen varchar(255), nombre varchar(120), observacion varchar(255), optLock int4, rif2 varchar(255), primary key (id));
create table SYST_Item (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, funcionId varchar(100), icono varchar(100), metodo varchar(100), nombre varchar(100), optLock int4, primary key (id));
create table SYST_Item_SYST_Item (SYST_Item_id int8 not null, items_id int8 not null, unique (items_id));
create table SYST_Licencia (id int8 not null, activo bool, activoTipDelDia bool, blockSize int4, codigoCamara varchar(255), descripcionEquipo varchar(80), fechaDesde timestamp, fechaHasta timestamp, nombreEquipo varchar(255), optLock int4, serialEquipo bytea not null, primary key (id));
create table SYST_Mensaje (PK_TPERDOC006 int8 not null, NB_ASUNTO varchar(255), de varchar(255), FE_ENVIO timestamp, FE_RESPUE timestamp, NU_LENENV int4, NU_LENRES int4, NB_FILENV varchar(255), NB_FILRES varchar(255), TX_MENENV varchar(255), TX_MENRES varchar(255), NB_EQUIPO varchar(255), OPTLOCK int4, para varchar(255), IN_PRIORI varchar(255), NB_USUENV varchar(255), NB_USURES varchar(255), primary key (PK_TPERDOC006));
create table SYST_MenuByRol (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, deletable bool, editable bool, enable bool, insertable bool, itemId int8, optLock int4, rolId int8, searchable bool, primary key (id));
create table SYST_ParametroReporte (id int8 not null, atributo varchar(120), operador varchar(255), OPTLOCK int4, valor varchar(255), primary key (id));
create table SYST_Reporte (id int8 not null, baseSQL varchar(3000), categoria varchar(255), file varchar(200), observacion varchar(300), optLock int4, tipo int4, tipoPapel varchar(255), titulo varchar(100), primary key (id));
create table SYST_Rol (id int8 not null, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, nombre varchar(100), optLock int4, primary key (id));
create table SYST_Usuario (id int8 not null, administraUsuarios bool, administrador bool, activo bool, borrable bool, editable2 bool, fechaInsert timestamp, fechaUpdate timestamp, observacion2 varchar(255), usuarioInsert varchar(255), usuarioUpdate varchar(255), visible2 bool, modificarPermisos bool, nombreCompleto varchar(100), optLock int4, password2 bytea, superusuario bool, userName varchar(20) unique, visible bool, rol_id int8, primary key (id));
alter table ALL_Documento add constraint FK62D73D56A530A49B foreign key (tipoDocumento_id) references ALL_TipoDocumento;
alter table ASEG_Asegurado add constraint FK982156D02CD1C7BA foreign key (id) references ASEG_Asegurado;
alter table ASEG_Asegurado add constraint FK982156D072F76D74 foreign key (certificado_id) references ASEG_Certificado;
alter table ASEG_Asegurado add constraint FK982156D0AA3C3FD5 foreign key (plazoEspera_id) references ASEG_PlazoEspera;
alter table ASEG_Asegurado add constraint FK982156D09B4BA0AB foreign key (plan_id) references ASEG_Plan;
alter table ASEG_Asegurado add constraint FK982156D0AD387041 foreign key (persona_id) references PERS_PersonaNatural;
alter table ASEG_Asegurado add constraint FK982156D04C5F0A8A foreign key (parentesco_id) references ASEG_Parentesco;
alter table ASEG_Asegurado_ALL_Documento add constraint FK367E3A27715B4769 foreign key (ASEG_Asegurado_id) references ASEG_Asegurado;
alter table ASEG_Asegurado_ALL_Documento add constraint FK367E3A272BAEDF50 foreign key (documentos_id) references ALL_Documento;
alter table ASEG_Asegurado_ALL_NotaTecnica add constraint FKF0A195508DBAEBCB foreign key (notasTecnicas_id) references ALL_NotaTecnica;
alter table ASEG_Asegurado_ALL_NotaTecnica add constraint FKF0A19550715B4769 foreign key (ASEG_Asegurado_id) references ASEG_Asegurado;
alter table ASEG_Asegurado_ALL_Observacion add constraint FK78E7F490715B4769 foreign key (ASEG_Asegurado_id) references ASEG_Asegurado;
alter table ASEG_Asegurado_ALL_Observacion add constraint FK78E7F490D98C3FAD foreign key (observaciones_id) references ALL_Observacion;
alter table ASEG_Beneficiario add constraint FKF2533E65D022151 foreign key (id) references ASEG_Beneficiario;
alter table ASEG_Beneficiario add constraint FKF2533E6572F76D74 foreign key (certificado_id) references ASEG_Certificado;
alter table ASEG_Beneficiario add constraint FKF2533E65AD387041 foreign key (persona_id) references PERS_PersonaNatural;
alter table ASEG_Beneficiario_ALL_Documento add constraint FKB084B8FC3E99C18B foreign key (ASEG_Beneficiario_id) references ASEG_Beneficiario;
alter table ASEG_Beneficiario_ALL_Documento add constraint FKB084B8FC2BAEDF50 foreign key (documentos_id) references ALL_Documento;
alter table ASEG_Beneficiario_ALL_NotaTecnica add constraint FK303B2E58DBAEBCB foreign key (notasTecnicas_id) references ALL_NotaTecnica;
alter table ASEG_Beneficiario_ALL_NotaTecnica add constraint FK303B2E53E99C18B foreign key (ASEG_Beneficiario_id) references ASEG_Beneficiario;
alter table ASEG_Beneficiario_ALL_Observacion add constraint FK8B4A12253E99C18B foreign key (ASEG_Beneficiario_id) references ASEG_Beneficiario;
alter table ASEG_Beneficiario_ALL_Observacion add constraint FK8B4A1225D98C3FAD foreign key (observaciones_id) references ALL_Observacion;
alter table ASEG_Certificado add constraint FK22003426431F6EDE foreign key (titular_id) references ASEG_Titular;
alter table ASEG_Certificado_ALL_Documento add constraint FKBE4C08FD9B3054BF foreign key (ASEG_Certificado_id) references ASEG_Certificado;
alter table ASEG_Certificado_ALL_Documento add constraint FKBE4C08FD2BAEDF50 foreign key (documentos_id) references ALL_Documento;
alter table ASEG_Certificado_ALL_NotaTecnica add constraint FKBC3706A69B3054BF foreign key (ASEG_Certificado_id) references ASEG_Certificado;
alter table ASEG_Certificado_ALL_NotaTecnica add constraint FKBC3706A68DBAEBCB foreign key (notasTecnicas_id) references ALL_NotaTecnica;
alter table ASEG_Certificado_ALL_Observacion add constraint FK447D65E69B3054BF foreign key (ASEG_Certificado_id) references ASEG_Certificado;
alter table ASEG_Certificado_ALL_Observacion add constraint FK447D65E6D98C3FAD foreign key (observaciones_id) references ALL_Observacion;
alter table ASEG_Poliza_ALL_Documento add constraint FK9273ED25BBA33FC9 foreign key (ASEG_Poliza_id) references ASEG_Poliza;
alter table ASEG_Poliza_ALL_Documento add constraint FK9273ED252BAEDF50 foreign key (documentos_id) references ALL_Documento;
alter table ASEG_Poliza_ALL_NotaTecnica add constraint FK25F680CE8DBAEBCB foreign key (notasTecnicas_id) references ALL_NotaTecnica;
alter table ASEG_Poliza_ALL_NotaTecnica add constraint FK25F680CEBBA33FC9 foreign key (ASEG_Poliza_id) references ASEG_Poliza;
alter table ASEG_Poliza_ALL_Observacion add constraint FKAE3CE00EBBA33FC9 foreign key (ASEG_Poliza_id) references ASEG_Poliza;
alter table ASEG_Poliza_ALL_Observacion add constraint FKAE3CE00ED98C3FAD foreign key (observaciones_id) references ALL_Observacion;
alter table ASEG_Poliza_ASEG_Certificado add constraint FKCCCF3DF7BBA33FC9 foreign key (ASEG_Poliza_id) references ASEG_Poliza;
alter table ASEG_Poliza_ASEG_Certificado add constraint FKCCCF3DF7C95CDCA3 foreign key (certificados_id) references ASEG_Certificado;
alter table ASEG_Titular add constraint FKD2E8A11C589C7E8A foreign key (departamento_id) references ASEG_Departamento;
alter table ASEG_Titular add constraint FKD2E8A11C48FBAF2A foreign key (tipoContrato_id) references ASEG_TipoContrato;
alter table ASEG_Titular add constraint FKD2E8A11CAD387041 foreign key (persona_id) references PERS_PersonaNatural;
alter table ASEG_Titular_ALL_Documento add constraint FKA2DF8F7338EDB3A9 foreign key (ASEG_Titular_id) references ASEG_Titular;
alter table ASEG_Titular_ALL_Documento add constraint FKA2DF8F732BAEDF50 foreign key (documentos_id) references ALL_Documento;
alter table ASEG_Titular_ALL_NotaTecnica add constraint FKCA02C79C8DBAEBCB foreign key (notasTecnicas_id) references ALL_NotaTecnica;
alter table ASEG_Titular_ALL_NotaTecnica add constraint FKCA02C79C38EDB3A9 foreign key (ASEG_Titular_id) references ASEG_Titular;
alter table ASEG_Titular_ALL_Observacion add constraint FK524926DC38EDB3A9 foreign key (ASEG_Titular_id) references ASEG_Titular;
alter table ASEG_Titular_ALL_Observacion add constraint FK524926DCD98C3FAD foreign key (observaciones_id) references ALL_Observacion;
alter table CONF_ConfiguracionPrima add constraint FK31C7B92FBEF5A115 foreign key (cobertura_id) references SINI_Cobertura;
alter table CONF_ConfiguracionPrima add constraint FK31C7B92F4C5F0A8A foreign key (parentesco_id) references ASEG_Parentesco;
alter table CONF_SumaAmparada add constraint FKC5C79E7A9B4BA0AB foreign key (plan_id) references ASEG_Plan;
alter table CONF_SumaAsegurada add constraint FK26FDBC3C75C391D2 foreign key (sumaAmparada_id) references CONF_SumaAmparada;
alter table CONF_SumaAsegurada add constraint FK26FDBC3C9B4BA0AB foreign key (plan_id) references ASEG_Plan;
alter table CONF_SumaAsegurada add constraint FK26FDBC3C7DB42274 foreign key (diagnostico_id) references SINI_Diagnostico;
alter table PAGO_OrdenDePago add constraint FK3EAF51DE648730EB foreign key (personaPago_id) references PERS_Persona;
alter table PAGO_OrdenDePago_ALL_Documento add constraint FKED78C4B55118E7FC foreign key (PAGO_OrdenDePago_id) references PAGO_OrdenDePago;
alter table PAGO_OrdenDePago_ALL_Documento add constraint FKED78C4B52BAEDF50 foreign key (documentos_id) references ALL_Documento;
alter table PAGO_OrdenDePago_ALL_NotaTecnica add constraint FKD323B45E8DBAEBCB foreign key (notasTecnicas_id) references ALL_NotaTecnica;
alter table PAGO_OrdenDePago_ALL_NotaTecnica add constraint FKD323B45E5118E7FC foreign key (PAGO_OrdenDePago_id) references PAGO_OrdenDePago;
alter table PAGO_OrdenDePago_ALL_Observacion add constraint FK5B6A139E5118E7FC foreign key (PAGO_OrdenDePago_id) references PAGO_OrdenDePago;
alter table PAGO_OrdenDePago_ALL_Observacion add constraint FK5B6A139ED98C3FAD foreign key (observaciones_id) references ALL_Observacion;
alter table PAGO_OrdenDePago_SINI_DetalleSiniestro add constraint FKE72097086BA773E2 foreign key (detalleSiniestros_id) references SINI_DetalleSiniestro;
alter table PAGO_OrdenDePago_SINI_DetalleSiniestro add constraint FKE72097085118E7FC foreign key (PAGO_OrdenDePago_id) references PAGO_OrdenDePago;
alter table PAGO_Remesa_PAGO_OrdenDePago add constraint FK44D282FE85D69D8B foreign key (ordenDePagos_id) references PAGO_OrdenDePago;
alter table PAGO_Remesa_PAGO_OrdenDePago add constraint FK44D282FE20259558 foreign key (PAGO_Remesa_id) references PAGO_Remesa;
alter table PERS_CuentaBancariaPersona add constraint FK806AA19E7A2BD9E1 foreign key (tipoCuenta_id) references PERS_TipoCuentaBancaria;
alter table PERS_CuentaBancariaPersona add constraint FK806AA19EED1010B5 foreign key (banco_id) references PERS_Persona;
alter table PERS_DefaultPersona add constraint FKA4FBFAB4A672607C foreign key (direccion_id) references PERS_TipoDireccion;
alter table PERS_DefaultPersona add constraint FKA4FBFAB4CC1424B8 foreign key (actividadEconomica_id) references PERS_TipoActividadEconomica;
alter table PERS_DefaultPersona add constraint FKA4FBFAB49136E2C6 foreign key (telefono_id) references PERS_TipoTelefono;
alter table PERS_DefaultPersona add constraint FKA4FBFAB48D6598D8 foreign key (capacidadEconomica_id) references PERS_TipoCapacidadEconomica;
alter table PERS_DireccionPersona add constraint FK4500AAA5F36185B0 foreign key (tipoDireccion_id) references PERS_TipoDireccion;
create index rifPersonaIndex on PERS_Persona (rif);
create index cedulaCompletaPersonaIndex on PERS_Persona (cedulaCompleta);
create index nombreLargoPersona on PERS_Persona (nombreLargo);
create index nombreCortoPersona on PERS_Persona (nombreCorto);
alter table PERS_Persona add constraint FKA2362343CC1424B8 foreign key (actividadEconomica_id) references PERS_TipoActividadEconomica;
alter table PERS_Persona add constraint FKA23623438D6598D8 foreign key (capacidadEconomica_id) references PERS_TipoCapacidadEconomica;
alter table PERS_PersonaJuridica add constraint FK321B63C85C446AB1 foreign key (id) references PERS_Persona;
alter table PERS_PersonaNatural add constraint FK5860EB665C446AB1 foreign key (id) references PERS_Persona;
alter table PERS_Persona_ALL_Documento add constraint FK43CEC15ADD415D0D foreign key (PERS_Persona_id) references PERS_Persona;
alter table PERS_Persona_ALL_Documento add constraint FK43CEC15A2BAEDF50 foreign key (documentos_id) references ALL_Documento;
alter table PERS_Persona_ALL_Observacion add constraint FK74337B03DD415D0D foreign key (PERS_Persona_id) references PERS_Persona;
alter table PERS_Persona_ALL_Observacion add constraint FK74337B03D98C3FAD foreign key (observaciones_id) references ALL_Observacion;
alter table PERS_Persona_PERS_CuentaBancariaPersona add constraint FKC40C41AC5A90969 foreign key (cuentasBancarias_id) references PERS_CuentaBancariaPersona;
alter table PERS_Persona_PERS_CuentaBancariaPersona add constraint FKC40C41ADD415D0D foreign key (PERS_Persona_id) references PERS_Persona;
alter table PERS_Persona_PERS_DireccionPersona add constraint FKD945EAA998D49C45 foreign key (direcciones_id) references PERS_DireccionPersona;
alter table PERS_Persona_PERS_DireccionPersona add constraint FKD945EAA9DD415D0D foreign key (PERS_Persona_id) references PERS_Persona;
alter table PERS_Persona_PERS_Sucursal add constraint FKF211F1CDDD415D0D foreign key (PERS_Persona_id) references PERS_Persona;
alter table PERS_Persona_PERS_Sucursal add constraint FKF211F1CDF5CF3DA2 foreign key (sucursales_id) references PERS_Sucursal;
alter table PERS_Persona_PERS_TelefonoPersona add constraint FK44E4FE2BDD415D0D foreign key (PERS_Persona_id) references PERS_Persona;
alter table PERS_Persona_PERS_TelefonoPersona add constraint FK44E4FE2B6068F506 foreign key (telefonos_id) references PERS_TelefonoPersona;
alter table PERS_Persona_PERS_TipoPersona add constraint FK125C4F6BDD415D0D foreign key (PERS_Persona_id) references PERS_Persona;
alter table PERS_Persona_PERS_TipoPersona add constraint FK125C4F6BF769787B foreign key (tiposPersona_id) references PERS_TipoPersona;
alter table PERS_Sucursal_PERS_DireccionPersona add constraint FK716CECAF98D49C45 foreign key (direcciones_id) references PERS_DireccionPersona;
alter table PERS_Sucursal_PERS_DireccionPersona add constraint FK716CECAF1BC2147 foreign key (PERS_Sucursal_id) references PERS_Sucursal;
alter table PERS_Sucursal_PERS_TelefonoPersona add constraint FKDE72A3656068F506 foreign key (telefonos_id) references PERS_TelefonoPersona;
alter table PERS_Sucursal_PERS_TelefonoPersona add constraint FKDE72A3651BC2147 foreign key (PERS_Sucursal_id) references PERS_Sucursal;
alter table PERS_TelefonoPersona add constraint FK1F144EAF9BF44712 foreign key (tipoTelefono_id) references PERS_TipoTelefono;
alter table PERS_TelefonoPersona add constraint FK1F144EAF5336F798 foreign key (codigoArea_id) references PERS_TELF_TipoCodigoArea;
alter table SINI_Cobertura add constraint FK7E622F457663F6FF foreign key (ramo_id) references CONF_Ramo;
alter table SINI_DesgloseCobertura add constraint FKE01F93BBEF5A115 foreign key (cobertura_id) references SINI_Cobertura;
alter table SINI_DesgloseSumaAsegurada add constraint FK5FD0C7DF3A4D06D6 foreign key (factura_id) references SINI_Factura;
alter table SINI_DesgloseSumaAsegurada add constraint FK5FD0C7DFA6F39A7F foreign key (diagnosticoSiniestro_id) references SINI_DiagnosticoSiniestro;
alter table SINI_DetalleSiniestro add constraint FK7190DEA986D3DC75 foreign key (siniestro_id) references SINI_Siniestro;
alter table SINI_DetalleSiniestro add constraint FK7190DEA942CA1156 foreign key (analistaNegociador_id) references PERS_Persona;
alter table SINI_DetalleSiniestro add constraint FK7190DEA9D218673 foreign key (etapaSiniestro_id) references SINI_EtapaSiniestro;
alter table SINI_DetalleSiniestro add constraint FK7190DEA9303BD281 foreign key (tipoSiniestro_id) references SINI_TipoSiniestro;
alter table SINI_DetalleSiniestro add constraint FK7190DEA9230EA9B0 foreign key (tipoPersona_id) references PERS_TipoPersona;
alter table SINI_DetalleSiniestro add constraint FK7190DEA97663F6FF foreign key (ramo_id) references CONF_Ramo;
alter table SINI_DetalleSiniestro add constraint FK7190DEA9648730EB foreign key (personaPago_id) references PERS_Persona;
alter table SINI_DetalleSiniestro_ALL_Documento add constraint FK41B29240371808B1 foreign key (SINI_DetalleSiniestro_id) references SINI_DetalleSiniestro;
alter table SINI_DetalleSiniestro_ALL_Documento add constraint FK41B292402BAEDF50 foreign key (documentos_id) references ALL_Documento;
alter table SINI_DetalleSiniestro_ALL_NotaTecnica add constraint FK204B298DBAEBCB foreign key (notasTecnicas_id) references ALL_NotaTecnica;
alter table SINI_DetalleSiniestro_ALL_NotaTecnica add constraint FK204B29371808B1 foreign key (SINI_DetalleSiniestro_id) references SINI_DetalleSiniestro;
alter table SINI_DetalleSiniestro_ALL_Observacion add constraint FK8866AA69371808B1 foreign key (SINI_DetalleSiniestro_id) references SINI_DetalleSiniestro;
alter table SINI_DetalleSiniestro_ALL_Observacion add constraint FK8866AA69D98C3FAD foreign key (observaciones_id) references ALL_Observacion;
alter table SINI_Diagnostico add constraint FKA90124DAB256D200 foreign key (especialidad_id) references SINI_Especialidad;
alter table SINI_DiagnosticoSiniestro add constraint FK63FCB298A6CB8F5F foreign key (detalleSiniestro_id) references SINI_DetalleSiniestro;
alter table SINI_DiagnosticoSiniestro add constraint FK63FCB2987DB42274 foreign key (diagnostico_id) references SINI_Diagnostico;
alter table SINI_DiagnosticoSiniestro_SINI_Tratamiento add constraint FKC90769C9617399C1 foreign key (tratamientos_id) references SINI_Tratamiento;
alter table SINI_DiagnosticoSiniestro_SINI_Tratamiento add constraint FKC90769C9DEDF1AD1 foreign key (SINI_DiagnosticoSiniestro_id) references SINI_DiagnosticoSiniestro;
alter table SINI_Especialidad add constraint FKA44E94407663F6FF foreign key (ramo_id) references CONF_Ramo;
alter table SINI_EtapaSiniestro add constraint FKAE608A1DA07DE4B3 foreign key (estatusSiniestro_id) references SINI_EstatusSiniestro;
alter table SINI_Factura add constraint FK58673BAAFF602E5E foreign key (tipoConceptoSeniat_id) references CONF_ConceptoSENIAT;
alter table SINI_Factura add constraint FK58673BAAA6CB8F5F foreign key (detalleSiniestro_id) references SINI_DetalleSiniestro;
alter table SINI_Factura_SINI_DesgloseCobertura add constraint FK6F191D707F8FBAEF foreign key (desgloseCobertura_id) references SINI_DesgloseCobertura;
alter table SINI_Factura_SINI_DesgloseCobertura add constraint FK6F191D7020DD6944 foreign key (SINI_Factura_id) references SINI_Factura;
alter table SINI_MantenimientoDiagnostico add constraint FKE8BB5B90A6F39A7F foreign key (diagnosticoSiniestro_id) references SINI_DiagnosticoSiniestro;
alter table SINI_Presupuesto add constraint FKDE0452E542CA1156 foreign key (analistaNegociador_id) references PERS_Persona;
alter table SINI_Siniestro add constraint FKD448920472F76D74 foreign key (certificado_id) references ASEG_Certificado;
alter table SINI_Siniestro add constraint FKD4489204B60B095E foreign key (asegurado_id) references ASEG_Asegurado;
alter table SINI_Tratamiento add constraint FK20A237027DB42274 foreign key (diagnostico_id) references SINI_Diagnostico;
alter table SYST_Item_SYST_Item add constraint FK478D3171705E1AE foreign key (SYST_Item_id) references SYST_Item;
alter table SYST_Item_SYST_Item add constraint FK478D31791AB0ED9 foreign key (items_id) references SYST_Item;
alter table SYST_Usuario add constraint FK43C0E165FEB600E foreign key (rol_id) references SYST_Rol;
create sequence hibernate_sequence start 1 increment 1;
